# Generated by Django 5.2.7 on 2025-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamItem',
            fields=[
                ('id_stream', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('avg_viewers', models.IntegerField(default=0)),
                ('max_viewers', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField(default=0)),
                ('view_minutes', models.IntegerField(default=0)),
                ('follower_gain', models.IntegerField(default=0)),
                ('games_played', models.ManyToManyField(to='streamle.game')),
            ],
        ),
    ]
