# Generated by Django 5.2.7 on 2025-10-24 06:37

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrandle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='scranitem',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scranitem',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scranitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=123, upload_to='', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scranitem',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrandle.country'),
        ),
        migrations.AddField(
            model_name='scranitem',
            name='tags',
            field=models.ManyToManyField(related_name='scrans', to='scrandle.tag'),
        ),
    ]
